services:
  node:
    build: 
      context: '../app/docker'
      cache_from:
        - node:18
        - ghcr.io/antode/tags-izbushka_node:latest
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: ghcr.io/antode/tags-izbushka_node:latest
    volumes:
      - '../app:/app'
      - './cache/node/.npm:/home/node/.npm'
      - './cache/node/.cache:/home/node/.cache'
    init: true
    ports: [ '${NODE_PORT}:5173' ]
    command: ['npm', 'run', 'dev', '--', '--host', '0.0.0.0']
