name: CI
on:
  push:
    branches:
      - ci
jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Docker login
      #   run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Cache Docker Build
        uses: actions/cache@v3
        with:
          key: cache-docker-build
          path: ${{ github.workspace }}/docker-compose/cache/.build

      - name: Install
        run: make install

      - name: Cache Node
        uses: actions/cache@v3
        with:
          key: cache-node
          path: ${{ github.workspace }}/docker-compose/cache/node/
      
      - name: Install e2e
        run: make install-e2e

      - name: Check
        run: make check