name: CI
on:
  push:
    branches:
      - ci
jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: docker login
        run: docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Help
        run: make help
