name: CI
on:
  push:
    branches:
      - ci
jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Help
        run: make install
